export const DEFAULT_ICON = new URL('@/assets/img/file.png', import.meta.url).href;
export const APP_NAME:string = 'SIPANDAI';
export const DEFAULT_PADDING_X:string = ' px-4 sm:px-8 lg:px-20 ';
export const DEFAULT_PADDING_X_MINUS:string = ' -mx-4 sm:-mx-8 lg:-mx-20 ';
export const DEFAULT_PADDING_Y:string = ' py-2 sm:py-4 ';
export const DEFAULT_PADDING_Y_MD:string = ' py-4 sm:py-8 ';
export const DEFAULT_PADDING_Y_LG:string = ' py-4 sm:py-8 lg:py-12';
export const DEFAULT_LABEL : string = ' block mb-2 text-sm sm:text-base font-medium text-gray-900 '
export const DEFAULT_INPUT : string = ' bg-gray-50 border border-gray-300 text-gray-900 text-sm sm:text-base rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 '
export const DEFAULT_INPUT_FILE : string = ' block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50  '